apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "dataproduct-new"
  namespace: broda-group-software
  title: "Data Product New"
  description: "Data Product New Description"
  # labels:
  # annotations:
  tags: ["tag-1"]
  # links:
spec:
  # Reserved fields
  type: data-product
  lifecycle: "experimental"
  owner: "user:guest"
  system: "system-1"
  subcomponentOf: "parent-1"
  providesApis: ["somePublishedAPI"]
  consumesApis: ["someConsumedAPI"]
  dependsOn: ["component:dataproduct-001"]

  # Custom fields
  # Sampel for schemas: https://datahubproject.io/docs/metadata-service (Retrieving Entity Aspects section)
  summarySpecification: "https://api.github.com/repos/ericbroda/data-mesh-product-new/contents/specification-summary.yaml"
  apiSpecification: "https://api.github.com/repos/ericbroda/data-mesh-product-new/contents/specification-api.json"
  schemaSpecification: "https://api.github.com/repos/ericbroda/data-mesh-product-new/contents/specification-schema.yaml"
  querySpecification: "https://api.github.com/repos/ericbroda/data-mesh-product-new/contents/specification-query.yaml"
  eventSpecification: "https://api.github.com/repos/ericbroda/data-mesh-product-new/contents/specification-event.yaml"
